#ifndef _LIBLANDEVICEUTILS_LANDEVICEUTILSTYPES_H_
#define _LIBLANDEVICEUTILS_LANDEVICEUTILSTYPES_H_

namespace LDU {

	enum ProtocolEnum {
		PROTOCOL_UNKNOWN = 0,
		PROTOCOL_EQ3LANIFCFG = 1,
		PROTOCOL_EQ3CONFIG = 2
	};

	enum RoutingSchemeEnum {
		ROUTINGSCHEME_UNICAST = 1,
		ROUTINGSCHEME_MULTICAST = 2,
		ROUTINGSCHEME_BROADCAST = 4,
	};
}
#endif