# TCP Port for XmlRpc connections
Listen Port = 2001

# Where to log: Console, Syslog, File. Syslog only under Linux
# Syslog is default on Linux, File is default on Windows
#Log Destination = File

# For "Log Destination = File", the log file name goes here
# strftime() style escape sequences may be used to achieve
# a kind of log rotation.
# The following line is already the default value on Windows
#Log File = c:\bidcos\logs\bidcos-%Y-%m-%d.log

# Log Level: 1=DEBUG, 2=WARNING, 3=INFO, 4=NOTICE, 5=WARNING, 6=ERROR
# Default is Info
#Log Level = 1

Persist Keys = 1

# Interface definitions:
# Every Interface has it's own section.
# The section name must start with "Interface" and be unique throughout this file.
[Interface 0]
# This section describes a Lan Interface connected via ethernet
Type = Lan Interface
Serial Number = REE0000001
Description = Test Device 1
# IP Addess is optional. If not specified, the Lan Interface is 
# detected by its serial number.
IP Address = 192.168.1.195

#[Interface 1]
#Type = CCU Builtin